# Generated by Django 4.2 on 2025-11-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
