# Generated by Django 4.2 on 2025-11-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_producer_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produtor', 'verbose_name_plural': 'Produtores'},
        ),
    ]
