# Generated by Django 4.2 on 2025-11-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farm_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fazenda', 'verbose_name_plural': 'Fazendas'},
        ),
    ]
