# Generated by Django 4.2 on 2025-11-26 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Colheita',
                'verbose_name_plural': 'Colheitas',
                'db_table': 'crop',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HarvestSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de início da safra')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de término da safra')),
            ],
            options={
                'verbose_name': 'Safra agrícola',
                'verbose_name_plural': 'Safras agrícolas',
                'db_table': 'harvest_seasons',
                'ordering': ['-start_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FarmCrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm_crop', to='cultivation.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_crop', to='farm.farm')),
                ('harvest_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm_crop', to='cultivation.harvestseason')),
            ],
            options={
                'verbose_name': 'Farm Crop',
                'verbose_name_plural': 'Farm Crops',
                'db_table': 'farm_crop',
            },
        ),
        migrations.AddConstraint(
            model_name='farmcrop',
            constraint=models.UniqueConstraint(fields=('farm', 'harvest_season', 'crop'), name='unique_farm_harvest_crop'),
        ),
    ]
