# Generated by Django 4.2 on 2025-11-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='harvestseason',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
