# Generated by Django 4.2 on 2025-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0002_crop_is_active_farmcrop_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
