# Generated by Django 4.2 on 2025-11-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0004_populate_crops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmcrop',
            options={'verbose_name': 'Cultivo Agrícola', 'verbose_name_plural': 'Cultivos Agrícolas'},
        ),
    ]
