# Generated by Django 4.2 on 2025-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0005_alter_farmcrop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmcrop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cultivo Agrícola', 'verbose_name_plural': 'Cultivos Agrícolas'},
        ),
        migrations.AlterField(
            model_name='harvestseason',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
